services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME:-gestionscolaire}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-binta}'
      - 'POSTGRES_USER=${DB_USERNAME:-postgres}'
    ports:
      - '5432:5432'
