# Application name
spring.application.name=GestionScolaire

# PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionscolaire
spring.datasource.username=postgres
spring.datasource.password=binta
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Security with JWT
jwt.secret=almanard3s_secret_key_2024_very_long_key_for_security
jwt.expiration=86400000

# Server port
server.port=8080
